

profile_picture = "//div[@class='container']//img"
main_picture = "//div[@class='bg']"
btn_go_to_category = "name:new_category"
btn_go_back = "name:go_back"
form = "//form"
footer = "//footer"
txt_name_heading = "//h1[@class='heading name']"
txt_main_text_para = "//p[@class='paragraph']"
txt_main_form_heading = "//h1[contains(text(), 'New')]"
txt_new_category = "name:category"
btn_new_category = "name:new_category"
txt_new_skill = "name:skill"
cmb_cat = "name:category"
btn_add_skill = "name:add"
tbl_skills = "//table"
btn_facebook = "id:facebook"
btn_linkedin = "id:linkedin"
btn_log_out = "id:logout"
btn_delete = "id:delete"
txt_heading = "//h1[@class='heading']"
lnk_error_page = "//a[@id='main']"
