
profile_picture = "//div[@class='container']//img"
main_picture = "//div[@class='top']"
btn_go_to_category = "name:new_category"
btn_go_back = "name:go_back"
form = "//form"
footer = "//footer"
txt_name_heading = "//h1[@class='heading name']"
txt_main_text_para = "//p[@class='paragraph']"
txt_main_form_heading = "//h1[contains(text(), 'New')]"
txt_new_category = "name:category"
btn_new_category = "name:new_category"
txt_new_skill = "name:skill"
cmb_cat = "name:category"
btn_add_skill = "name:add"
tbl_skills = "//table"
btn_facebook = "id:facebook"
btn_linkedin = "id:linkedin"
btn_log_out = "id:logout"
btn_delete = "id:delete_account"
txt_heading = "//h1[@class='heading']"
lnk_error_page = "//a[@id='main']"
txt_greeting = "//div[@class='col-md-4 text-right']//h4"
txt_token = "//div[@class='col-md-4 text-right']//p/strong[1]"
txt_token_expiration = "//div[@class='col-md-4 text-right']//p/strong[2]"
txt_deletion_info = "//div[@class='col-md-4 text-right']//p"

